version: '3.8'

services:
  app:
    # Use the Maven image directly for development to run from source code
    image: maven:3.9.6-eclipse-temurin-17
    container_name: expense-app
    working_dir: /app
    # Mount the local project and the local .m2 cache
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    # Command to run Spring Boot with devtools live reload
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    environment:
      # Override the local config to point to the docker network aliases
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/expense_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  mysql:
    image: mysql:8.0
    container_name: expense-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: expense-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      mysql:
        condition: service_healthy

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: expense-kafka-ui
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

volumes:
  mysql_data:
